// <auto-generated />
namespace MVCEnrollmentApplication.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Lab7Part2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Lab7Part2));
        
        string IMigrationMetadata.Id
        {
            get { return "201903010336220_Lab7Part2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
