// <auto-generated />
namespace MVCEnrollmentApplication.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Lab7Part1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Lab7Part1));
        
        string IMigrationMetadata.Id
        {
            get { return "201902280031340_Lab7Part1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
